---
- name: "Setup {{component}} for Roboshop"
  hosts: "{{component}}"
  # hosts: localhost
  become: yes
  vars_files: variables_root.yaml
  tasks:
    - name: "Running {{component}} role"
      ansible.builtin.import_role:
        name: "{{component}}"