- name: configure yum erlang repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: configure yum rabbitmq repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash


- name: install rabbitmq server
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: enable and starte rabbtitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: creating user for roboshop and setting permsissions to user
  ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

- name: creating user for roboshop and setting permsissions to user
  ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"