- name: add roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Create a app directory if it does not exist for roboshop
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Download {{component}} application source code zip file"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "Extract {{component}}.zip to /app directory"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes