- name: "copy {{component}} svc file"
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system

- name: realod daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable {{component}}"
  ansible.builtin.service:
    name: "{{component}}"
    state: started
    enabled: yes